# Generated by Django 2.2.4 on 2019-10-14 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ability',
            fields=[
                ('name', models.CharField(default='Provoke', max_length=200)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='AugmentedEquipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Gil', max_length=255)),
                ('description', models.CharField(default='Money', max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='Cornelia', max_length=255)),
                ('server', models.CharField(default='Server', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Gil', max_length=255)),
                ('description', models.CharField(default='Money', max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('en', models.CharField(default='None', max_length=200)),
                ('ja', models.CharField(default='なし', max_length=200)),
                ('ens', models.CharField(default='NON', max_length=200)),
                ('jas', models.CharField(blank=True, default='', max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Loadout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('name', models.CharField(default='Ear3', max_length=200)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Spell',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('en', models.CharField(default='Cure', max_length=200)),
                ('ja', models.CharField(default='ケアル', max_length=200)),
                ('cast_time', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('element', models.IntegerField(default=0)),
                ('icon_id', models.IntegerField(default=0)),
                ('icon_id_nq', models.IntegerField(default=0)),
                ('mp_cost', models.IntegerField(default=1)),
                ('prefix', models.CharField(default='/magic', max_length=200)),
                ('spell_range', models.IntegerField(default=0)),
                ('recast', models.DecimalField(decimal_places=2, default=1, max_digits=5)),
                ('recast_id', models.IntegerField(default=0)),
                ('requirements', models.IntegerField(default=0)),
                ('skill', models.IntegerField(default=1)),
                ('targets', models.IntegerField(default=1)),
                ('spell_type', models.CharField(default='WhiteMagic', max_length=200)),
                ('duration', models.IntegerField(default=0)),
                ('status', models.IntegerField(default=0)),
                ('unlearnable', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Weaponskill',
            fields=[
                ('name', models.CharField(default='Dominion Slash', max_length=200)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
    ]
